### ISSUE TITLE
Missing migrations for id

### ISSUE THREAD

**Issue by fjsj** [simonw/django-sql-dashboard#103]
Got this when trying to deploy version 0.13:
```
Migrations for 'django_sql_dashboard':
  venv/lib/python3.8/site-packages/django_sql_dashboard/migrations/0004_auto_20210511_1039.py
    - Alter field id on dashboard
    - Alter field id on dashboardquery
```

**Comment by simonw** [comment]
I think this relates to the new default primary key in https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys - not entirely sure how this should work.

**Comment by fjsj** [comment]
Makes sense. I've configured `DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"`.

Maybe setting the app-level `AppConfig.default_auto_field` config solves that? https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.AppConfig.default_auto_field

**Comment by simonw** [comment]
Yes that looks like the solution: https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

> To avoid unwanted migrations in the future, either explicitly set [`DEFAULT_AUTO_FIELD`](https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-DEFAULT_AUTO_FIELD) to [`AutoField`](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.AutoField "django.db.models.AutoField"):
> ```python
> DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
> ```
> or configure it on a per-app basis:
> ```python
> from django.apps import AppConfig
> 
> class MyAppConfig(AppConfig):
>     default_auto_field = 'django.db.models.AutoField'
>     name = 'my_app'
> ```
