### ISSUE TITLE
Make specific Black version a test dependency, enforce with GitHub actions

### ISSUE THREAD

**Issue by toolness** [simonw/django-sql-dashboard#119]
The contribution documentation mentions that the codebase uses Black, but it doesn't mention what version... I know that Prettier (which I'm more familiar with) recommends pinning to a particular version, since its (rather opinionated) formatting can change from one version to the next... is Black the same, or are its formatting guidelines more set-in-stone?

Anyhow, I thought that it would also be nice to run `black --check`, either as part of the `test.yml` GitHub workflow or wrapped in a pytest test.  That way you'd be able to tell if new PRs are using proper formatting.

**Comment by simonw** [comment]
I do this on my other projects, not sure why I forgot about that here.
