### ISSUE TITLE
Pip installation missing urls.py

### ISSUE THREAD

**Issue by chriswedgwood** [simonw/django-sql-dashboard#21]
Hi @simonw  this looks cool. Ive run into a hiccup with the install.

pip installed django-sql-dashboard
pip freeze says django-sql-dashboard==0.1a3 

path("dashboard/", include(django_sql_dashboard.urls)),
AttributeError: module 'django_sql_dashboard' has no attribute 'urls'

![image](https://user-images.githubusercontent.com/1273523/111088493-603ca680-851f-11eb-906e-4203898e8036.png)

Got  it working with manually creating urls.py.

**Comment by chriswedgwood** [comment]
Oh I see you just need to publish to Pypi with the github action.
I'll give this a test drive tomorrow, looks really great

**Comment by simonw** [comment]
Yes new alpha is coming out shortly, hopefully that will work straight after installation!

**Comment by simonw** [comment]
Aah I see what happened here, the README installation instructions no longer match the package that is available on PyPI.

**Comment by simonw** [comment]
Should be fixed by the new 0.2a0 alpha release that just pushed to PyPI.
