### ISSUE TITLE
Django 3.1 migration dependency

### ISSUE THREAD

**Issue by jefftriplett** [simonw/django-sql-dashboard#46]
I noticed an error when I installed this with Django 3.0 because you have a migration that's tied to `0012_alter_user_first_name_max_length` which is a 3.1 feature. 

Maybe this is intentional, but an updated trove classifier and/or a setup requirement of 3.1 might at least let people know. 

https://github.com/simonw/django-sql-dashboard/blob/main/django_sql_dashboard/migrations/0002_dashboard_permissions.py#L12

**Comment by simonw** [comment]
Not intentional, I'll fix that - thanks!

**Comment by simonw** [comment]
Looks like I can just delete that dependency line entirely.

**Comment by simonw** [comment]
Released in https://github.com/simonw/django-sql-dashboard/releases/tag/0.4a2

**Comment by Xzya** [comment]
This is still happening to me in the latest version (1.0.1) and Django 3.0.7.
