### ISSUE TITLE
Turn [count] into a cog action menu item, add more

### ISSUE THREAD

**Issue by simonw** [simonw/django-sql-dashboard#57]
Borrow the cog action menu design from Datasette. Actions can include:

- Count values (the existing "count" link)
- Sum / Avg / etc (for columns that are numbers)
- Show not-null values

**Comment by MoralCode** [comment]
sort by ascending/descending might be useful to add to a menu like this as well

**Comment by simonw** [comment]
Yes, that's a great idea.

**Comment by simonw** [comment]
Here's what I implemented to start with:

![cog](https://user-images.githubusercontent.com/9599/124050047-91f25400-d9ce-11eb-8d69-a113fc8bcda8.gif)

**Comment by MoralCode** [comment]
small nitpick: a settings icon may not be the _most_ correct thing to use here and something that looks more like a filter or funnel may be a better choice to make the UI super clear

**Comment by simonw** [comment]
I'm using the same icon I used for Datasette, see https://github.com/simonw/datasette/issues/981#issuecomment-701664306.

I thought about using a filter icon but those to me imply tools for narrowing down the selection, which isn't what's happening here. I also tried using a ▼ icon but that looked too much like it was a "sort descending" indicator.

**Comment by MoralCode** [comment]
could a "three dots" type icon work?
