### ISSUE TITLE
CSV and JSON export

### ISSUE THREAD

**Issue by simonw** [simonw/django-sql-dashboard#8]
Ala Datasette

**Comment by simonw** [comment]
CSV export will only work with a single `?swl=` query I think (the first one)

I'm not going to attempt more than the first page of results for the moment - that's more of a streaming/ASGI trick (that's how Datasette does it) - it also requires efficient pagination. Might get to that eventually.

**Comment by simonw** [comment]
(Exporting entire tables to CSV using keyset pagination would be a really interesting project to start experimenting with ASGI in Django)

**Comment by simonw** [comment]
See also #50

**Comment by simonw** [comment]
I'm happy with the CSV/TSV export I built in #50 - closing this for now.

**Comment by river-matt** [comment]
+1 for json support. I love the way it works in datasette. I'm currently experimenting with js visualization libraries and this would be an awesome tool for to the development lifecycle of those. Add in parameters and this would be really really powerful.

Also, I love the work you're doing on this and datasette. It's nice that you publish your thought process as issues - it's good documentation! Thank you!
