### ISSUE TITLE
Bar charts sort labels alphabetically instead of respecting their order

### ISSUE THREAD

**Issue by simonw** [simonw/django-sql-dashboard#93]
<img width="1143" alt="SQL__select__tag__as_bar_label__count____as_bar_quantity_from__select___from_blog_entry_tags_join_blog_tag_on_blog_tag_id___blog_entry_tags_tag_id__as_results_group_by__tag__order_by_bar_quantity_desc" src="https://user-images.githubusercontent.com/9599/117690206-72c60b80-b16f-11eb-99e8-f50b81827346.png">

Pointed out here: https://twitter.com/zellyn/status/1391786830333464579

**Comment by simonw** [comment]
I am finding it remarkably difficult to figure out how to get Vega-Lite bar charts to respect the initial order (I remember having this same problem with `datasette-vega`): https://vega.github.io/vega-lite/docs/bar.html

**Comment by aborruso** [comment]
@simonw I do not know if it's ok for you. have you tried with `"sort": {"field": "fieldname"}`?


Here an example <https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiiA4NkgIEGgA2qCy4XBoIFBs6rJw6gBKSMo0DJFKxEiCDAmoAAxKTDSyymig1TgMmInqSLJkCUoI1WgVIMgAHmhifRCYcDhoAIwAvjMAukr+gXUghcVq0aAoBsFMaABMABwzCtuJAEJ7w2Kn5+gAwteoACwAzHcgOyAAIs8AnLMzl9EgBRZ5HIH3EAAMWeYg+wO+AHFnlN-p9vgAJCEAdkxiQAkvCDgtTv0bABrVaYACeOFKIGs6mCyVS6SyOTyqzgAxwLPQbLSmWyuUicyUcFkyRy7VWQ1QoAAZjQ4IJaugUEo6QzErI2N04oJgkgBjRIoqQIIkJ5BPp2hZeuSZOpmpaVWqNUyQBKQLTVh71Yl9tr6YyAI4MNo6QI6Ug+uZAA>

**Comment by simonw** [comment]
That's not quite what I'm after here - I want to sort in the order originally provided by the results of the query.

So if the data looked like this:

```json
  {
    "values": [
      {"a": "Dog", "b": 28},
      {"a": "Cat", "b": 55},
      {"a": "Chicken", "b": 43},
      {"a": "Dragon", "b": 91}
    ]
  }
```
I want the bars on the bar chart to be in `Dog`, `Cat`, `Chicken`, `Dragon` order.

**Comment by simonw** [comment]
Aha! It looks like `"sort": null` does the trick. https://vega.github.io/vega-lite/docs/sort.html#no-sorting

**Comment by simonw** [comment]
https://simonwillison.net/dashboard/bar-chart-for-issue-93/ before this fix:

<img width="1129" alt="Bar_chart_for_issue_93" src="https://user-images.githubusercontent.com/9599/118311473-cfddfc00-b4a4-11eb-9c76-16942b8e5b48.png">

After the fix:

<img width="1132" alt="Bar_chart_for_issue_93" src="https://user-images.githubusercontent.com/9599/118311636-0451b800-b4a5-11eb-9edc-0e91edca95fc.png">

**Comment by simonw** [comment]
I can fix https://github.com/simonw/datasette-vega/issues/19 with this too.
